import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AttributionCapture } from "@/components/attribution-capture";
import { OpenInApp } from "@/components/open-in-app";
import { ShareButton } from "@/components/share-button";
import { canonicalUrl } from "@/lib/sharing";
import { createClient, hasSupabaseEnv } from "@/lib/supabase/server";

type Item={post_id:string;kind:string;caption:string|null;published_at:string;proof_id:string|null;media_kind:"image"|"video"|null;media_public_url:string|null};
type Journey={id:string;display_name:string;handle:string|null;challenge_slug:string;challenge_title:string;attempt_no:number;status:string;verified_count:number;current_streak:number;best_streak:number;timeline:Item[]};
async function load(id:string){if(!hasSupabaseEnv())return null;const{data}=await(await createClient()).rpc("get_journey_snapshot_v1",{target_journey:id});return data as Journey|null;}
export async function generateMetadata({params}:{params:Promise<{journeyId:string}>}):Promise<Metadata>{const{journeyId}=await params;const j=await load(journeyId);if(!j)return{title:"Journey not available"};const title=`${j.display_name} · ${j.challenge_title} Journey`;const description=`Attempt ${j.attempt_no}. ${j.verified_count} verified receipts. Best streak ${j.best_streak}.`;const path=`/j/${journeyId}`;return{title,description,alternates:{canonical:path},openGraph:{title,description,url:canonicalUrl(path),type:"website"}};}
export default async function JourneyPage({params,searchParams}:{params:Promise<{journeyId:string}>;searchParams:Promise<{src?:string}>}){const{journeyId}=await params;const{src}=await searchParams;const j=await load(journeyId);if(!j)notFound();const path=`/j/${journeyId}`;return <main className="app-wrap wide-wrap"><AttributionCapture source={src?.slice(0,40)||"journey_link"} path={path}/><section className="section"><span className="tag">JOURNEY · ATTEMPT {j.attempt_no} · {j.status.toUpperCase()}</span><h1>{j.display_name}<br/>{j.challenge_title}</h1><div className="signal-strip"><div><span>VERIFIED</span><strong>{j.verified_count}</strong></div><div><span>CURRENT</span><strong>{j.current_streak}</strong></div><div><span>BEST</span><strong>{j.best_streak}</strong></div></div><div className="actions"><OpenInApp path={path}/><ShareButton title={`${j.display_name}'s Journey`} text={`Follow ${j.handle?`@${j.handle}`:j.display_name} on ${j.challenge_title}.`} path={path} source="journey_share"/><Link className="btn" href={`/c/${j.challenge_slug}`}>Join same Drop →</Link></div></section><section className="section"><h2>THE TIMELINE.</h2><div className="receipt-grid">{(j.timeline||[]).map(item=><article className="proof-card receipt-tile" key={item.post_id}>{item.media_kind==="image"&&item.media_public_url&&<img src={item.media_public_url} alt="Journey post"/>}<div className="proof-body"><strong>{item.kind.toUpperCase()}</strong><p>{item.caption||"ProofMode post."}</p><Link href={`/p/${item.post_id}`}>Open post →</Link></div></article>)}</div></section></main>;}
