import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AttributionCapture } from "@/components/attribution-capture";
import { OpenInApp } from "@/components/open-in-app";
import { canonicalUrl } from "@/lib/sharing";
import { createClient, hasSupabaseEnv } from "@/lib/supabase/server";

type Invite={code:string;challenge_id:string;challenge_slug:string;challenge_title:string;challenge_rule:string;challenge_tagline:string|null;challenge_duration_days:number;challenge_visibility:string;cover_emoji:string|null;inviter_handle:string|null;inviter_display_name:string|null};
async function load(code:string){if(!hasSupabaseEnv())return null;const{data}=await(await createClient()).rpc("resolve_invite_share_v1",{target_code:code});return data as Invite|null;}
export async function generateMetadata({params}:{params:Promise<{code:string}>}):Promise<Metadata>{const{code}=await params;const i=await load(code);if(!i)return{title:"Invite not available"};const inviter=i.inviter_handle?`@${i.inviter_handle}`:i.inviter_display_name||"A friend";const title=`${inviter} challenged you: ${i.challenge_title}`;const description=i.challenge_tagline||i.challenge_rule;const path=`/invite/${code}`;return{title,description,alternates:{canonical:path},openGraph:{title,description,url:canonicalUrl(path),type:"website"}};}
export default async function InvitePage({params,searchParams}:{params:Promise<{code:string}>;searchParams:Promise<{src?:string}>}){const{code}=await params;const{src}=await searchParams;const i=await load(code);if(!i)notFound();const path=`/invite/${code}`;const inviter=i.inviter_handle?`@${i.inviter_handle}`:i.inviter_display_name||"A ProofMode member";return <main className="app-wrap"><AttributionCapture source={src?.slice(0,40)||"invite_link"} inviteCode={code} path={path}/><section className="panel"><span className="tag">YOU WERE CALLED OUT</span><div style={{fontSize:56}}>{i.cover_emoji||"↗"}</div><h1>{i.challenge_title}</h1><p className="section-lede">{inviter} wants you in. {i.challenge_tagline||i.challenge_rule}</p><div className="actions"><OpenInApp path={path} source="invite_link" label="Open invite in app →"/><form action="/api/join" method="post"><input type="hidden" name="slug" value={i.challenge_slug}/><input type="hidden" name="inviteCode" value={code}/><button className="btn btn-primary" type="submit">Accept challenge →</button></form><Link className="btn" href={`/c/${i.challenge_slug}?ref=${encodeURIComponent(code)}`}>View Drop on web →</Link></div></section></main>;}
